### PR TITLE
Fix phonetics for 樂

### PR DESCRIPTION
**Pull request by xatier**
Adding the following two from the concise dictionary:

```text
作樂	ㄗㄨㄛˋ ㄌㄜˋ
悶悶不樂	ㄇㄣˋ ㄇㄣˋ ㄅㄨˊ ㄌㄜˋ
```

- `ㄌㄜˋ` from the concise dictionary:

```text
不亦樂乎 ㄅㄨˊ ㄧˋ ㄌㄜˋ ㄏㄨ
不亦樂乎 ㄅㄨˋ ㄧˋ ㄌㄜˋ ㄏㄨ
不樂 ㄅㄨˊ ㄌㄜˋ
不樂 ㄅㄨˋ ㄌㄜˋ
不樂觀 ㄅㄨˊ ㄌㄜˋ ㄍㄨㄢ
不樂觀 ㄅㄨˋ ㄌㄜˋ ㄍㄨㄢ
享樂 ㄒㄧㄤˇ ㄌㄜˋ
伯樂 ㄅㄛˊ ㄌㄜˋ
何樂不為 ㄏㄜˊ ㄌㄜˋ ㄅㄨˋ ㄨㄟˊ
作樂 ㄗㄨㄛˋ ㄌㄜˋ
俱樂部 ㄐㄩˋ ㄌㄜˋ ㄅㄨˋ
兒童樂園 ㄦˊ ㄊㄨㄥˊ ㄌㄜˋ ㄩㄢˊ
其樂融融 ㄑㄧˊ ㄌㄜˋ ㄖㄨㄥˊ ㄖㄨㄥˊ
取樂 ㄑㄩˇ ㄌㄜˋ
可樂 ㄎㄜˇ ㄌㄜˋ
吃喝玩樂 ㄔ ㄏㄜ ㄨㄢˊ ㄌㄜˋ
同樂 ㄊㄨㄥˊ ㄌㄜˋ
同樂會 ㄊㄨㄥˊ ㄌㄜˋ ㄏㄨㄟˋ
和樂 ㄏㄜˊ ㄌㄜˋ
哀樂 ㄞ ㄌㄜˋ
喜怒哀樂 ㄒㄧˇ ㄋㄨˋ ㄞ ㄌㄜˋ
天倫之樂 ㄊㄧㄢ ㄌㄨㄣˊ ㄓ ㄌㄜˋ
娛樂 ㄩˊ ㄌㄜˋ
娛樂場所 ㄩˊ ㄌㄜˋ ㄔㄤˇ ㄙㄨㄛˇ
娛樂稅 ㄩˊ ㄌㄜˋ ㄕㄨㄟˋ
安和樂利 ㄢ ㄏㄜˊ ㄌㄜˋ ㄌㄧˋ
安居樂業 ㄢ ㄐㄩ ㄌㄜˋ ㄧㄝˋ
安樂 ㄢ ㄌㄜˋ
安樂死 ㄢ ㄌㄜˋ ㄙˇ
安樂窩 ㄢ ㄌㄜˋ ㄨㄛ
安貧樂道 ㄢ ㄆㄧㄣˊ ㄌㄜˋ ㄉㄠˋ
富強康樂 ㄈㄨˋ ㄑㄧㄤˊ ㄎㄤ ㄌㄜˋ
寓教於樂 ㄩˋ ㄐㄧㄠˋ ㄩˊ ㄌㄜˋ
尋樂 ㄒㄩㄣˊ ㄌㄜˋ
幸災樂禍 ㄒㄧㄥˋ ㄗㄞ ㄌㄜˋ ㄏㄨㄛˋ
康樂 ㄎㄤ ㄌㄜˋ
康樂活動 ㄎㄤ ㄌㄜˋ ㄏㄨㄛˊ ㄉㄨㄥˋ
快樂 ㄎㄨㄞˋ ㄌㄜˋ
怏怏不樂 ㄧㄤˋ ㄧㄤˋ ㄅㄨˊ ㄌㄜˋ
怏怏不樂 ㄧㄤˋ ㄧㄤˋ ㄅㄨˋ ㄌㄜˋ
悅樂 ㄩㄝˋ ㄌㄜˋ
悶悶不樂 ㄇㄣˋ ㄇㄣˋ ㄅㄨˊ ㄌㄜˋ
悶悶不樂 ㄇㄣˋ ㄇㄣˋ ㄅㄨˋ ㄌㄜˋ
找樂子 ㄓㄠˇ ㄌㄜˋ ㄗ˙
極樂 ㄐㄧˊ ㄌㄜˋ
極樂世界 ㄐㄧˊ ㄌㄜˋ ㄕˋ ㄐㄧㄝˋ
樂不可支 ㄌㄜˋ ㄅㄨˋ ㄎㄜˇ ㄓ
樂不思蜀 ㄌㄜˋ ㄅㄨˋ ㄙ ㄕㄨˇ
樂事 ㄌㄜˋ ㄕˋ
樂利 ㄌㄜˋ ㄌㄧˋ
樂善 ㄌㄜˋ ㄕㄢˋ
樂善好施 ㄌㄜˋ ㄕㄢˋ ㄏㄠˋ ㄕ
樂園 ㄌㄜˋ ㄩㄢˊ
樂土 ㄌㄜˋ ㄊㄨˇ
樂在其中 ㄌㄜˋ ㄗㄞˋ ㄑㄧˊ ㄓㄨㄥ
樂天 ㄌㄜˋ ㄊㄧㄢ
樂天派 ㄌㄜˋ ㄊㄧㄢ ㄆㄞˋ
樂天知命 ㄌㄜˋ ㄊㄧㄢ ㄓ ㄇㄧㄥˋ
樂子 ㄌㄜˋ ㄗ˙
樂意 ㄌㄜˋ ㄧˋ
樂捐 ㄌㄜˋ ㄐㄩㄢ
樂極生悲 ㄌㄜˋ ㄐㄧˊ ㄕㄥ ㄅㄟ
樂此不疲 ㄌㄜˋ ㄘˇ ㄅㄨˋ ㄆㄧˊ
樂而忘返 ㄌㄜˋ ㄦˊ ㄨㄤˋ ㄈㄢˇ
樂觀 ㄌㄜˋ ㄍㄨㄢ
樂觀其成 ㄌㄜˋ ㄍㄨㄢ ㄑㄧˊ ㄔㄥˊ
樂趣 ㄌㄜˋ ㄑㄩˋ
樂陶陶 ㄌㄜˋ ㄊㄠˊ ㄊㄠˊ
歡樂 ㄏㄨㄢ ㄌㄜˋ
津津樂道 ㄐㄧㄣ ㄐㄧㄣ ㄌㄜˋ ㄉㄠˋ
狄斯耐樂園 ㄉㄧˊ ㄙ ㄋㄞˋ ㄌㄜˋ ㄩㄢˊ
玩樂 ㄨㄢˊ ㄌㄜˋ
知足常樂 ㄓ ㄗㄨˊ ㄔㄤˊ ㄌㄜˋ
育樂 ㄩˋ ㄌㄜˋ
自得其樂 ㄗˋ ㄉㄜˊ ㄑㄧˊ ㄌㄜˋ
芭樂 ㄅㄚ ㄌㄜˋ
苦中作樂 ㄎㄨˇ ㄓㄨㄥ ㄗㄨㄛˋ ㄌㄜˋ
苦樂 ㄎㄨˇ ㄌㄜˋ
逸樂 ㄧˋ ㄌㄜˋ
遊樂 ㄧㄡˊ ㄌㄜˋ
遊樂場 ㄧㄡˊ ㄌㄜˋ ㄔㄤˇ
電視遊樂器 ㄉㄧㄢˋ ㄕˋ ㄧㄡˊ ㄌㄜˋ ㄑㄧˋ
鬱鬱不樂 ㄩˋ ㄩˋ ㄅㄨˊ ㄌㄜˋ
鬱鬱不樂 ㄩˋ ㄩˋ ㄅㄨˋ ㄌㄜˋ
```

Also add some 不 variants.

https://dict.concised.moe.edu.tw/search.jsp?md=1&word=%E6%A8%82&size=-1

### CODE REVIEW

**Comment by lukhnos** [comment]
Thanks again for the efforts. I think the phrase additions are fine, but I'm not sure if adding "不

**Comment by lukhnos** [comment]
Thanks for the efforts. I think the phrase additions are fine, but are we sure that the readings like 不

**Comment by lukhnos** [comment]
Thanks again for the efforts. I think the phrase additions are fine, but I'm not sure if adding "ㄅㄨˋ ㄌㄜˋ" really helps anyone? I feel this is yet another example of how a dictionary has prescriptive entries that run counter to how they are actually used or read, and I think this is where we should make a call saying this is really not how the language is used (by this community of input method users).

**Comment by xatier** [comment]
Agreed, ideally we should have some polls on the PRs or user surveys to better understand the usage.

**Review by lukhnos — CHANGES_REQUESTED** [review]
Based on our discussion in the other PRs, I'd suggest we keep the entries that are new additions, but remove all the 不- phrases. I'm also fine with 狄斯耐,` but just wanted to point our that there's 迪斯耐 [sic] in the dictionary. My impression is that until the franchise had officially registered themselves as the 迪士尼 as we know it today, various translations existed.

**Comment by xatier** [comment]
@lukhnos I'd like to get an explicit confirmation that you'd like me to remove all these phrases.

```
不亦樂乎 ㄅㄨˋ ㄧˋ ㄌㄜˋ ㄏㄨ
不樂 ㄅㄨˋ ㄌㄜˋ
不樂觀 ㄅㄨˊ ㄌㄜˋ ㄍㄨㄢ
不樂觀 ㄅㄨˋ ㄌㄜˋ ㄍㄨㄢ
怏怏不樂 ㄧㄤˋ ㄧㄤˋ ㄅㄨˋ ㄌㄜˋ
悶悶不樂 ㄇㄣ ㄇㄣ ㄅㄨˋ ㄌㄜˋ
悶悶不樂 ㄇㄣ ㄇㄣˋ ㄅㄨˋ ㄌㄜˋ
悶悶不樂 ㄇㄣˋ ㄇㄣˋ ㄅㄨˊ ㄌㄜˋ
悶悶不樂 ㄇㄣˋ ㄇㄣˋ ㄅㄨˋ ㄌㄜˋ
鬱鬱不樂 ㄩˋ ㄩˋ ㄅㄨˊ ㄌㄜˋ
鬱鬱不樂 ㄩˋ ㄩˋ ㄅㄨˋ ㄌㄜˋ
```

I have these as we had the agreement with this rule: `若「不」後面接四聲，該「不」應為二聲 (變調)，但四聲「不」 (原調) 也應一併加入詞庫` [1] from my previous PR regarding `不` phrases.

I'd like to know if we are abandoning this rule now, if so, we should also update the wiki. Personally, I'm fine with either keeping or removing it, but would like to see @tianjianjiang's opinion on this.

[1] https://github.com/openvanilla/McBopomofo/wiki/%E8%A9%9E%E5%BA%AB%E9%96%8B%E7%99%BC%E8%AA%AA%E6%98%8E#%E9%99%84%E9%8C%84%E5%90%AB%E4%B8%8D%E7%9A%84%E5%A4%9A%E5%AD%97%E8%A9%9E%E8%AE%80%E9%9F%B3%E4%BF%AE%E6%AD%A3

**Comment by lukhnos** [comment]
Ah, thanks for the reminder. Since we have agreed upon the rules, I think we should follow through.

@tianjianjiang Thoughts?

**Comment by tianjianjiang** [comment]
> Ah, thanks for the reminder. Since we have agreed upon the rules, I think we should follow through.
> 
> @tianjianjiang Thoughts?

@lukhnos @xatier I think it's good to follow the conventions of keeping/adding original tones while adding their tone sandhi entries.

**Comment by xatier** [comment]
In that case, I believe we can keep this PR as-is.

**Review by lukhnos — APPROVED** [review]
Thanks!

**Pull request merged**
