### PR TITLE
Add missing character 萜

### PR DESCRIPTION
**Pull request by xatier**
Ref:

https://en.wiktionary.org/wiki/%E8%90%9C
https://www.wikiwand.com/zh-tw/%E8%90%9C%E7%83%AF
https://www.wikiwand.com/zh-tw/%E7%B1%BB%E8%90%9C

### CODE REVIEW

**Comment by xatier** [comment]
Terpenes and terpenoids 💨

**Comment by ChiahongHong** [comment]
Great! Although it won't affect the actual outcome, should we change the encoding of this character  from `big5` to `utf8` to maintain encoding correctness before removing the encoding field as discussed in https://github.com/openvanilla/McBopomofo/pull/491#issuecomment-2161376260?

**Comment by xatier** [comment]
Sure thing, fixed! Thanks for the advice!

**Comment by tianjianjiang** [comment]
雖然可能不常這樣寫，但我有點好奇「萜烯烴」會不會正確地轉換出來，還是會變成「萜烯聽」或其他的組合。

**Comment by ChiahongHong** [comment]
@tianjianjiang

I think this special case is inherently difficult to predict the outcome, so it should be fine.

If necessary, we can also add `萜烯烴` to the list.

https://github.com/openvanilla/McBopomofo/assets/36815907/1cf8c21e-df83-4c1c-b804-be58464b623b

**Comment by tianjianjiang** [comment]
> @tianjianjiang
> 
> I think this special case is inherently difficult to predict the outcome, so it should be fine.
> 
> If necessary, we can also add `萜烯烴` to the list.

@ChiahongHong 
Thank you for the usage video, that's really helpful.

I also anticipate that difficult situation. As long as it is still acceptible to you (and hopefully the online learning algorithm will kick in soon enough), I have no strong preference for adding 萜烯烴 or not.

**Review by lukhnos — APPROVED** [review]
Thanks!

**Pull request merged**
