### PR TITLE
Add missing character 絝

### PR DESCRIPTION
**Pull request by xatier**
Ref: https://www.moedict.tw/%E7%B5%9D

@lukhnos, I noticed a typo in this section [1], it should be `BPMFMappings.txt`. I suspect this file was not sorted properly due to the typo.

[1] https://github.com/openvanilla/McBopomofo/wiki/%E8%A9%9E%E5%BA%AB%E9%96%8B%E7%99%BC%E8%AA%AA%E6%98%8E#%E8%AB%8B%E7%A2%BA%E4%BF%9D-bpmfmappingtxt-%E4%BB%A5%E5%8F%8A-phraseocc-%E5%85%A9%E5%80%8B%E6%AA%94%E6%A1%88%E7%9A%84%E8%A9%9E%E6%A2%9D%E6%8E%92%E5%BA%8F

### CODE REVIEW

**Comment by xatier** [comment]
Adding this since I wasn't able to type 紈絝子弟 (紈褲子弟) :D

**Comment by tianjianjiang** [comment]
@xatier Would you mind not including the sorted BPMFMappings.txt in this PR? I personally prefer having a PR as small and specific as possible. +CC @lukhnos

**Comment by xatier** [comment]
I wouldn't mind reverting the second commit, I was just following the wiki and ran the commands in that section.

**Comment by lukhnos** [comment]
> I wouldn't mind reverting the second commit, I was just following the wiki and ran the commands in that section.

Could you please revert the `LC_ALL=c sort` commit for this PR? I'll make a sort PR later.

Thanks for pointing out the typo. It's embarrassing that when I prepared the previous sort PR, [the script I used](https://gist.github.com/lukhnos/2d4c628e2690b5407777f2b75f699a89) only sorted the keys but didn't sort the value, and then I asked everyone to run `LC_ALL=c sort`… An example of one not following one's own advice for others. :p

**Review by tianjianjiang — APPROVED** [review]

**Pull request merged**
