### PR TITLE
Keep BPMFMappings.txt and phrase.occ sorted

### LINKED ISSUE #447: Keep BPMFMapping.txt and phrase.occ sorted
From @xatier:

> On the ordering issue, I have this little script locally to keep my user dictionary nice and neat, I would suggest having sometime similar in this repo.

https://gist.github.com/xatier/9f34fb64884e3cbfd66f24716beb6e7a

_Originally posted by @xatier in https://github.com/openvanilla/McBopomofo/issues/437#issuecomment-1962227613_

### PR DESCRIPTION
**Pull request by lukhnos**
Fixes #447

This also dedups phrase.occ and fixes a few issues with phrases such as 電子 (vs 靛紫) due to the inadvertent dups having much lower scores.

`phrase.occ` sorted and deduped with a one-time script: https://gist.github.com/lukhnos/2d4c628e2690b5407777f2b75f699a89

cc @xatier

### CODE REVIEW

**Comment by xatier** [comment]
Thank you so much for this change! This will make the dictionary way easier to maintainable.  Let's also update the wiki once this is merged [1] 

[1] https://github.com/openvanilla/McBopomofo/wiki/%E8%A9%9E%E5%BA%AB%E9%96%8B%E7%99%BC%E8%AA%AA%E6%98%8E

**Review by tianjianjiang — APPROVED** [review]
@lukhnos I've tried to read the diffs but too complex to be consistently verified, so I just approve this and then make a plan of reimplementing an algorithm to verify it systematically.

**Comment by lukhnos** [comment]
> @lukhnos I've tried to read the diffs but too complex to be consistently verified, so I just approve this and then make a plan of reimplementing an algorithm to verify it systematically.

Sorry to make this too complex. Here the diff against the current `phrase.occ`—first sorted with `LC_ALL=c sort` and all tabs replaced with single spaces—against the one in the PR: [diff](https://gist.githubusercontent.com/lukhnos/44451adea1fa426b5f9e7a7bf650c386/raw/11a6b7ac207ff7393d2a3abcf6c8133e545808e4/phrase.occ.diff). There are 26 entries removed, and that's how I discovered that those dups had contributed to issues such as "電子" might not always come before "墊子".

I'll merge this now, and hopefully after the sorting we'll have an easier time reviewing these files.

**Comment by tianjianjiang** [comment]
> > @lukhnos I've tried to read the diffs but too complex to be consistently verified, so I just approve this and then make a plan of reimplementing an algorithm to verify it systematically.
> 
> Sorry to make this too complex. Here the diff against the current `phrase.occ`—first sorted with `LC_ALL=c sort` and all tabs replaced with single spaces—against the one in the PR: [diff](https://gist.githubusercontent.com/lukhnos/44451adea1fa426b5f9e7a7bf650c386/raw/11a6b7ac207ff7393d2a3abcf6c8133e545808e4/phrase.occ.diff). There are 26 entries removed, and that's how I discovered that those dups had contributed to issues such as "電子" might not always come before "墊子".
> 
> I'll merge this now, and hopefully after the sorting we'll have an easier time reviewing these files.

@lukhnos No worries at all and thank you so much for the clarification!

**Comment by lukhnos** [comment]
> Let's also update the wiki once this is merged

增加了一節 https://github.com/openvanilla/McBopomofo/wiki/詞庫開發說明#請確保-bpmfmappingtxt-以及-phraseocc-兩個檔案的詞條排序

**Pull request merged**
