### PR TITLE
Add some missing Taichung districts

### PR DESCRIPTION
**Pull request by xatier**
Fix typo of 石岡

Ref: https://zh.wikipedia.org/wiki/%E8%87%BA%E4%B8%AD%E5%B8%82?oldformat=true#%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83%E5%92%8C%E4%BA%BA%E5%8F%A3

### CODE REVIEW

**Comment by xatier** [comment]
@lukhnos,

I wasn't able to type some places in my hometown, Taichung, hence having this PR to add the missing ones to the dictionary.

**Comment by xatier** [comment]
Also, may we get a minor release once this PR is merged and sync with the Linux repo? We have accumulated quite some updates in the dictionary.

https://github.com/openvanilla/McBopomofo/compare/2.7.2..master

**Review by tianjianjiang — CHANGES_REQUESTED** [review]
For the consistency with historical data like the case of 石岡鄉，I think there are some missing entries like 神岡鄉、清水鎮、龍荓鄉，and more.

**Comment by xatier** [comment]
While I don't find it necessary to include the old names, I've updated my PR for consistency.

> 民國八十五年（1996年）太平鄉升格為縣轄市，臺中縣至廢除前下轄3市（豐原市、大里市、太平市）、5鎮（大甲鎮、清水鎮、沙鹿鎮、梧棲鎮、東勢鎮）、13鄉（龍井鄉、大肚鄉、大安鄉、外埔鄉、后里鄉、潭子鄉、大雅鄉、神岡鄉、石岡鄉、新社鄉、霧峰鄉、烏日鄉，和平鄉為山地鄉）

src: https://www.wikiwand.com/zh-tw/%E8%87%BA%E4%B8%AD%E7%B8%A3#%E6%AD%B7%E5%8F%B2%E5%B9%B4%E8%A1%A8

**Review by tianjianjiang — APPROVED** [review]
@xatier Thank you so much!

**Comment by xatier** [comment]
Thanks!

**Pull request merged**
