### PR TITLE
Fix phonetics for 液

### PR DESCRIPTION
**Pull request by xatier**
The concise dictionary prefers `液 ㄧㄝˋ`

https://dict.concised.moe.edu.tw/search.jsp?md=1&word=%E6%B6%B2&page=1

Add `ㄧㄝˋ` for the following phrases from the concise dictionary.

```
修正液
溶液
體液
黏液
```

Provide both variants for the following phrases to ensure consistency.

```
血液
液化
液晶
```

Ensure all `液 ㄧㄝˋ` phrases have `液 ㄧˋ` variants.

### CODE REVIEW

**Comment by xatier** [comment]
Now we have:

```text
$ ./find.py 液 ㄧㄝˋ
乙醇溶液 ㄧˇ ㄔㄨㄣˊ ㄖㄨㄥˊ ㄧˋ
乳化液 ㄖㄨˇ ㄏㄨㄚˋ ㄧˋ
乳液 ㄖㄨˇ ㄧˋ
乳液聚合 ㄖㄨˇ ㄧˋ ㄐㄩˋ ㄏㄜˊ
人工血液 ㄖㄣˊ ㄍㄨㄥ ㄒㄧㄝˇ ㄧˋ
修正液 ㄒㄧㄡ ㄓㄥˋ ㄧˋ
卸妝液 ㄒㄧㄝˋ ㄓㄨㄤ ㄧˋ
原液 ㄩㄢˊ ㄧˋ
唾液 ㄊㄨㄛˋ ㄧˋ
唾液腺 ㄊㄨㄛˋ ㄧˋ ㄒㄧㄢˋ
土壤溶液 ㄊㄨˇ ㄖㄤˇ ㄖㄨㄥˊ ㄧˋ
培養液 ㄆㄟˊ ㄧㄤˇ ㄧˋ
定影液 ㄉㄧㄥˋ ㄧㄥˇ ㄧˋ
尿液 ㄋㄧㄠˋ ㄧˋ
廢液 ㄈㄟˋ ㄧˋ
懸浮液 ㄒㄩㄢˊ ㄈㄨˊ ㄧˋ
懸液計 ㄒㄩㄢˊ ㄧˋ ㄐㄧˋ
懸濁液 ㄒㄩㄢˊ ㄓㄨㄛˊ ㄧˋ
染液 ㄖㄢˇ ㄧˋ
標準溶液 ㄅㄧㄠ ㄓㄨㄣˇ ㄖㄨㄥˊ ㄧˋ
樹液 ㄕㄨˋ ㄧˋ
毒液 ㄉㄨˊ ㄧˋ
水溶液 ㄕㄨㄟˇ ㄖㄨㄥˊ ㄧˋ
汁液 ㄓ ㄧˋ
汗液 ㄏㄢˋ ㄧˋ
油液 ㄧㄡˊ ㄧˋ
波爾多液 ㄅㄛ ㄦˇ ㄉㄨㄛ ㄧˋ
波爾多液 ㄆㄛ ㄦˇ ㄉㄨㄛ ㄧˋ
津液 ㄐㄧㄣ ㄧˋ
消化液 ㄒㄧㄠ ㄏㄨㄚˋ ㄧˋ
液力傳動 ㄧˋ ㄌㄧˋ ㄔㄨㄢˊ ㄉㄨㄥˋ
液化 ㄧˋ ㄏㄨㄚˋ
液化器 ㄧˋ ㄏㄨㄚˋ ㄑㄧˋ
液化天然氣 ㄧˋ ㄏㄨㄚˋ ㄊㄧㄢ ㄖㄢˊ ㄑㄧˋ
液化瓦斯 ㄧˋ ㄏㄨㄚˋ ㄨㄚˇ ㄙ
液化石油氣 ㄧˋ ㄏㄨㄚˋ ㄕˊ ㄧㄡˊ ㄑㄧˋ
液壓 ㄧˋ ㄧㄚ
液壓式 ㄧˋ ㄧㄚ ㄕˋ
液壓機 ㄧˋ ㄧㄚ ㄐㄧ
液壓油 ㄧˋ ㄧㄚ ㄧㄡˊ
液態 ㄧˋ ㄊㄞˋ
液態氧 ㄧˋ ㄊㄞˋ ㄧㄤˇ
液態空氣 ㄧˋ ㄊㄞˋ ㄎㄨㄥ ㄑㄧˋ
液晶 ㄧˋ ㄐㄧㄥ
液晶投影電視 ㄧˋ ㄐㄧㄥ ㄊㄡˊ ㄧㄥˇ ㄉㄧㄢˋ ㄕˋ
液晶板 ㄧˋ ㄐㄧㄥ ㄅㄢˇ
液晶片 ㄧˋ ㄐㄧㄥ ㄆㄧㄢˋ
液晶錶 ㄧˋ ㄐㄧㄥ ㄅㄧㄠˇ
液晶顯示器 ㄧˋ ㄐㄧㄥ ㄒㄧㄢˇ ㄕˋ ㄑㄧˋ
液氨 ㄧˋ ㄢ
液汁 ㄧˋ ㄓ
液泡 ㄧˋ ㄆㄠˋ
液胞膜 ㄧˋ ㄅㄠ ㄇㄛˋ
液體 ㄧˋ ㄊㄧˇ
液體動力 ㄧˋ ㄊㄧˇ ㄉㄨㄥˋ ㄌㄧˋ
液體燃料 ㄧˋ ㄊㄧˇ ㄖㄢˊ ㄌㄧㄠˋ
液體狀態 ㄧˋ ㄊㄧˇ ㄓㄨㄤˋ ㄊㄞˋ
淋巴液 ㄌㄧㄣˊ ㄅㄚ ㄧˋ
淚液 ㄌㄟˋ ㄧˋ
混合液 ㄏㄨㄣˋ ㄏㄜˊ ㄧˋ
溶液 ㄖㄨㄥˊ ㄧˋ
溶液聚合 ㄖㄨㄥˊ ㄧˋ ㄐㄩˋ ㄏㄜˊ
漿液 ㄐㄧㄤ ㄧˋ
濾液 ㄌㄩˋ ㄧˋ
玉液瓊漿 ㄩˋ ㄧˋ ㄑㄩㄥˊ ㄐㄧㄤ
瓊漿玉液 ㄑㄩㄥˊ ㄐㄧㄤ ㄩˋ ㄧˋ
硫酸液 ㄌㄧㄡˊ ㄙㄨㄢ ㄧˋ
稀釋液 ㄒㄧ ㄕˋ ㄧˋ
稀釋溶液 ㄒㄧ ㄕˋ ㄖㄨㄥˊ ㄧˋ
粉底液 ㄈㄣˇ ㄉㄧˇ ㄧˋ
粘液 ㄋㄧㄢˊ ㄧˋ
精液 ㄐㄧㄥ ㄧˋ
細胞液 ㄒㄧˋ ㄅㄠ ㄧˋ
組織液 ㄗㄨˇ ㄓ ㄧˋ
緩衝液 ㄏㄨㄢˇ ㄔㄨㄥ ㄧˋ
緩衝溶液 ㄏㄨㄢˇ ㄔㄨㄥ ㄖㄨㄥˊ ㄧˋ
肥皂液 ㄈㄟˊ ㄗㄠˋ ㄧˋ
胃液 ㄨㄟˋ ㄧˋ
胃液素 ㄨㄟˋ ㄧˋ ㄙㄨˋ
胰液 ㄧˊ ㄧˋ
腦液 ㄋㄠˇ ㄧˋ
膠體溶液 ㄐㄧㄠ ㄊㄧˇ ㄖㄨㄥˊ ㄧˋ
菌液 ㄐㄩㄣˋ ㄧˋ
葡萄糖液 ㄆㄨˊ ㄊㄠˊ ㄊㄤˊ ㄧˋ
蒸餾液 ㄓㄥ ㄌㄧㄡˋ ㄧˋ
藥液 ㄧㄠˋ ㄧˋ
血液 ㄒㄧㄝˇ ㄧˋ
血液凝固 ㄒㄧㄝˇ ㄧˋ ㄋㄧㄥˊ ㄍㄨˋ
血液循環 ㄒㄧㄝˇ ㄧˋ ㄒㄩㄣˊ ㄏㄨㄢˊ
血液檢驗 ㄒㄧㄝˇ ㄧˋ ㄐㄧㄢˇ ㄧㄢˋ
血液檢體 ㄒㄧㄝˇ ㄧˋ ㄐㄧㄢˇ ㄊㄧˇ
血液癌 ㄒㄧㄝˇ ㄧˋ ㄞˊ
血液癌 ㄒㄧㄝˇ ㄧˋ ㄧㄢˊ
血液科 ㄒㄧㄝˇ ㄧˋ ㄎㄜ
血液量 ㄒㄧㄝˇ ㄧˋ ㄌㄧㄤˋ
防蚊液 ㄈㄤˊ ㄨㄣˊ ㄧˋ
電解液 ㄉㄧㄢˋ ㄐㄧㄝˇ ㄧˋ
顯像液 ㄒㄧㄢˇ ㄒㄧㄤˋ ㄧˋ
顯影液 ㄒㄧㄢˇ ㄧㄥˇ ㄧˋ
體液 ㄊㄧˇ ㄧˋ
鹼液 ㄐㄧㄢˇ ㄧˋ
黏液 ㄋㄧㄢˊ ㄧˋ
```

```text
$ ./find.py 液 ㄧㄝˋ
乙醇溶液 ㄧˇ ㄔㄨㄣˊ ㄖㄨㄥˊ ㄧㄝˋ
乳化液 ㄖㄨˇ ㄏㄨㄚˋ ㄧㄝˋ
乳液 ㄖㄨˇ ㄧㄝˋ
乳液聚合 ㄖㄨˇ ㄧㄝˋ ㄐㄩˋ ㄏㄜˊ
人工血液 ㄖㄣˊ ㄍㄨㄥ ㄒㄧㄝˇ ㄧㄝˋ
修正液 ㄒㄧㄡ ㄓㄥˋ ㄧㄝˋ
原液 ㄩㄢˊ ㄧㄝˋ
唾液 ㄊㄨㄛˋ ㄧㄝˋ
唾液腺 ㄊㄨㄛˋ ㄧㄝˋ ㄒㄧㄢˋ
土壤溶液 ㄊㄨˇ ㄖㄤˇ ㄖㄨㄥˊ ㄧㄝˋ
培養液 ㄆㄟˊ ㄧㄤˇ ㄧㄝˋ
定影液 ㄉㄧㄥˋ ㄧㄥˇ ㄧㄝˋ
尿液 ㄋㄧㄠˋ ㄧㄝˋ
染液 ㄖㄢˇ ㄧㄝˋ
標準溶液 ㄅㄧㄠ ㄓㄨㄣˇ ㄖㄨㄥˊ ㄧㄝˋ
毒液 ㄉㄨˊ ㄧㄝˋ
水溶液 ㄕㄨㄟˇ ㄖㄨㄥˊ ㄧㄝˋ
汁液 ㄓ ㄧㄝˋ
汗液 ㄏㄢˋ ㄧㄝˋ
油液 ㄧㄡˊ ㄧㄝˋ
波爾多液 ㄅㄛ ㄦˇ ㄉㄨㄛ ㄧㄝˋ
波爾多液 ㄆㄛ ㄦˇ ㄉㄨㄛ ㄧㄝˋ
津液 ㄐㄧㄣ ㄧㄝˋ
消化液 ㄒㄧㄠ ㄏㄨㄚˋ ㄧㄝˋ
液力傳動 ㄧㄝˋ ㄌㄧˋ ㄔㄨㄢˊ ㄉㄨㄥˋ
液化 ㄧㄝˋ ㄏㄨㄚˋ
液化器 ㄧㄝˋ ㄏㄨㄚˋ ㄑㄧˋ
液化天然氣 ㄧㄝˋ ㄏㄨㄚˋ ㄊㄧㄢ ㄖㄢˊ ㄑㄧˋ
液化瓦斯 ㄧㄝˋ ㄏㄨㄚˋ ㄨㄚˇ ㄙ
液化石油氣 ㄧㄝˋ ㄏㄨㄚˋ ㄕˊ ㄧㄡˊ ㄑㄧˋ
液壓 ㄧㄝˋ ㄧㄚ
液壓式 ㄧㄝˋ ㄧㄚ ㄕˋ
液壓機 ㄧㄝˋ ㄧㄚ ㄐㄧ
液壓油 ㄧㄝˋ ㄧㄚ ㄧㄡˊ
液態 ㄧㄝˋ ㄊㄞˋ
液態氧 ㄧㄝˋ ㄊㄞˋ ㄧㄤˇ
液態空氣 ㄧㄝˋ ㄊㄞˋ ㄎㄨㄥ ㄑㄧˋ
液晶 ㄧㄝˋ ㄐㄧㄥ
液晶投影電視 ㄧㄝˋ ㄐㄧㄥ ㄊㄡˊ ㄧㄥˇ ㄉㄧㄢˋ ㄕˋ
液晶板 ㄧㄝˋ ㄐㄧㄥ ㄅㄢˇ
液晶片 ㄧㄝˋ ㄐㄧㄥ ㄆㄧㄢˋ
液晶錶 ㄧㄝˋ ㄐㄧㄥ ㄅㄧㄠˇ
液晶顯示器 ㄧㄝˋ ㄐㄧㄥ ㄒㄧㄢˇ ㄕˋ ㄑㄧˋ
液汁 ㄧㄝˋ ㄓ
液泡 ㄧㄝˋ ㄆㄠˋ
液胞膜 ㄧㄝˋ ㄅㄠ ㄇㄛˋ
液體 ㄧㄝˋ ㄊㄧˇ
液體動力 ㄧㄝˋ ㄊㄧˇ ㄉㄨㄥˋ ㄌㄧˋ
液體燃料 ㄧㄝˋ ㄊㄧˇ ㄖㄢˊ ㄌㄧㄠˋ
液體狀態 ㄧㄝˋ ㄊㄧˇ ㄓㄨㄤˋ ㄊㄞˋ
淋巴液 ㄌㄧㄣˊ ㄅㄚ ㄧㄝˋ
淚液 ㄌㄟˋ ㄧㄝˋ
混合液 ㄏㄨㄣˋ ㄏㄜˊ ㄧㄝˋ
溶液 ㄖㄨㄥˊ ㄧㄝˋ
溶液聚合 ㄖㄨㄥˊ ㄧㄝˋ ㄐㄩˋ ㄏㄜˊ
玉液瓊漿 ㄩˋ ㄧㄝˋ ㄑㄩㄥˊ ㄐㄧㄤ
稀釋溶液 ㄒㄧ ㄕˋ ㄖㄨㄥˊ ㄧㄝˋ
精液 ㄐㄧㄥ ㄧㄝˋ
組織液 ㄗㄨˇ ㄓ ㄧㄝˋ
緩衝液 ㄏㄨㄢˇ ㄔㄨㄥ ㄧㄝˋ
緩衝溶液 ㄏㄨㄢˇ ㄔㄨㄥ ㄖㄨㄥˊ ㄧㄝˋ
肥皂液 ㄈㄟˊ ㄗㄠˋ ㄧㄝˋ
胃液 ㄨㄟˋ ㄧㄝˋ
胃液素 ㄨㄟˋ ㄧㄝˋ ㄙㄨˋ
胰液 ㄧˊ ㄧㄝˋ
膠體溶液 ㄐㄧㄠ ㄊㄧˇ ㄖㄨㄥˊ ㄧㄝˋ
血液 ㄒㄧㄝˇ ㄧㄝˋ
血液凝固 ㄒㄧㄝˇ ㄧㄝˋ ㄋㄧㄥˊ ㄍㄨˋ
血液循環 ㄒㄧㄝˇ ㄧㄝˋ ㄒㄩㄣˊ ㄏㄨㄢˊ
血液檢驗 ㄒㄧㄝˇ ㄧㄝˋ ㄐㄧㄢˇ ㄧㄢˋ
血液檢體 ㄒㄧㄝˇ ㄧㄝˋ ㄐㄧㄢˇ ㄊㄧˇ
血液癌 ㄒㄧㄝˇ ㄧㄝˋ ㄞˊ
血液癌 ㄒㄧㄝˇ ㄧㄝˋ ㄧㄢˊ
血液科 ㄒㄧㄝˇ ㄧㄝˋ ㄎㄜ
血液量 ㄒㄧㄝˇ ㄧㄝˋ ㄌㄧㄤˋ
電解液 ㄉㄧㄢˋ ㄐㄧㄝˇ ㄧㄝˋ
體液 ㄊㄧˇ ㄧㄝˋ
黏液 ㄋㄧㄢˊ ㄧㄝˋ
```

**Comment by xatier** [comment]
Remaining phrases with ONLY `液 ㄧˋ` variants:

```diff
$ diff -u <(./find.py 液 ㄧㄝˋ| awk '{print $1}') <(./find.py 液 ㄧˋ| awk '{print $1}')
--- /dev/fd/63	2024-10-21 18:15:34.462574694 -0500
+++ /dev/fd/62	2024-10-21 18:15:34.462574694 -0500
@@ -4,6 +4,7 @@
 乳液聚合
 人工血液
 修正液
+卸妝液
 原液
 唾液
 唾液腺
@@ -11,8 +12,13 @@
 培養液
 定影液
 尿液
+廢液
+懸浮液
+懸液計
+懸濁液
 染液
 標準溶液
+樹液
 毒液
 水溶液
 汁液
@@ -41,6 +47,7 @@
 液晶片
 液晶錶
 液晶顯示器
+液氨
 液汁
 液泡
 液胞膜
@@ -53,9 +60,17 @@
 混合液
 溶液
 溶液聚合
+漿液
+濾液
 玉液瓊漿
+瓊漿玉液
+硫酸液
+稀釋液
 稀釋溶液
+粉底液
+粘液
 精液
+細胞液
 組織液
 緩衝液
 緩衝溶液
@@ -63,7 +78,12 @@
 胃液
 胃液素
 胰液
+腦液
 膠體溶液
+菌液
+葡萄糖液
+蒸餾液
+藥液
 血液
 血液凝固
 血液循環
@@ -73,6 +93,10 @@
 血液癌
 血液科
 血液量
+防蚊液
 電解液
+顯像液
+顯影液
 體液
+鹼液
 黏液
```

**Comment by tianjianjiang** [comment]
> Remaining phrases with ONLY `液 ㄧˋ` variants:

Does this imply that those will not be associated with /ye4/?

**Comment by xatier** [comment]
Correct.

**Comment by tianjianjiang** [comment]
> > > Remaining phrases with ONLY `液 ㄧˋ` variants:
> > 
> > Does this imply that those will not be associated with /ye4/?
>
> Correct.

Since https://dict.revised.moe.edu.tw/search.jsp?md=1&word=%E6%B6%B2&qMd=0&qCol=1&size=100 have a few more records than the concise dict, perhaps many terms can also have /ye4/. That being said, I won't insist.

The only case I find it may break consistency is

```diff
+漿液
...
 玉液瓊漿
+瓊漿玉液
```
if 玉液瓊漿 can have /ye4/, then I'd like at least 瓊漿玉液 to have it, too. (漿液 is just nice to have.)

**Comment by xatier** [comment]
fixed.

**Review by tianjianjiang — APPROVED** [review]
Thank you!

**Pull request merged**
