### PR TITLE
fix some BPMFMappings

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Just found some wrong BPMFMappings then send this PR to fix them.

### CODE REVIEW

**Comment by mjhsieh** [comment]
Please do this in your branch, and I will merge the PR. Thanks!

``` patch
diff --git a/Source/Data/BPMFMappings.txt b/Source/Data/BPMFMappings.txt
index 89dd09d..80924a4 100644
--- a/Source/Data/BPMFMappings.txt
+++ b/Source/Data/BPMFMappings.txt
@@ -68621,7 +68621,7 @@
 東廠 ㄉㄨㄥ ㄔㄤˇ
 東引 ㄉㄨㄥ ㄧㄣˇ
 東引島 ㄉㄨㄥ ㄧㄣˇ ㄉㄠˇ
-張西望 ㄉㄨㄥ ㄓㄤ ㄒㄧ ㄨㄤˋ
+東張西望 ㄉㄨㄥ ㄓㄤ ㄒㄧ ㄨㄤˋ
 東征 ㄉㄨㄥ ㄓㄥ
 東征西討 ㄉㄨㄥ ㄓㄥ ㄒㄧ ㄊㄠˇ
 東德 ㄉㄨㄥ ㄉㄜˊ
diff --git a/Source/Data/phrase.occ b/Source/Data/phrase.occ
index 79250db..0313a49 100644
--- a/Source/Data/phrase.occ
+++ b/Source/Data/phrase.occ
@@ -74968,7 +74968,6 @@
 死胎   1
 死胡同 6
 死腦筋 5
-死裏逃生       0
 死裡求生       0
 死裡逃生       10
 死褲子 0
```

**Comment by mjhsieh** [comment]
As to you porting the phrases to libchewing, you will have to worry about the licensing yourself, I guess. (mcbpmf - MIT, libchewing - GPLv3) (?)

**Comment by PeterDaveHello** [comment]
Okay, thanks for the mistake catch! About the license, libchewing is licensed under GNU LGPL v2.1, I thought it's okay to use MIT licensed works in LGPL v2.1, hope I didn't misunderstand something, I also add a notes about license info of McBopomofo in that PR, do you have any suggestion? Thanks.

**Comment by PeterDaveHello** [comment]
PR updated.

**Comment by mjhsieh** [comment]
the PR#105 doesn't look right, it doesn't include this PR #101

**Pull request merged**
