### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by lukhnos**

### CODE REVIEW

**Comment by lukhnos** [comment]
According to [GitHub's doc](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project):

> Your code of conduct will be available either way, but "Code of conduct" will only be marked as complete in your repository's community profile if you use a template.

Let's put `CODE_OF_CONDUCT.md` at repo root for general purposes, and we can point people to [the Traditional Chinese version](https://www.contributor-covenant.org/translations/) in `README.md`.

**Comment by ShikiSuen** [comment]
請問這份檔案是用來規範 discussion 的用法的、還是也用來規範對 codebase 的貢獻行為的？

我是覺得 review 過程有必要走兩遍。我在同步（作為上游的）這邊的時候偶爾會看到一些被認為 LGTM 的 bug。
因為是 MIT 專案，所以不會產生任何責任。
只是有些 bug 要是盡量在 review 過程中被發現的話，或許可以降低 main branch （小麥這邊是 master branch）的熵。

**Comment by zonble** [comment]
I am OK with that. :) How about @mjhsieh ?

**Comment by mjhsieh** [comment]
LGTM

**Pull request merged**
