### PR TITLE
Fix missing character 犇 (fixed #473)

### LINKED ISSUE #473: [詞庫問題回報] 缺字: 犇
**分類**

- [o ] 缺字/詞

**說明**
阿宅我要查漢堡王犇牛肉堡價錢的時候發現找不到字🤣
犇，「[奔]」的異體字，音ㄅㄣ

**相關資料**
https://dict.revised.moe.edu.tw/dictView.jsp?ID=16955&la=0&powerMode=0

### PR DESCRIPTION
**Pull request by xatier**

### CODE REVIEW

**Comment by xatier** [comment]
@lukhnos please kindly take a look. :pray:

**Review by lukhnos — APPROVED** [review]

**Comment by xatier** [comment]
thank you!

**Comment by xatier** [comment]
@lukhnos btw, would you mind making another sync to `fcitx5-mcbopomofo` repo? As a Linux user, I'd like to receive the recent dictionary updates.

**Comment by lukhnos** [comment]
> @lukhnos btw, would you mind making another sync to `fcitx5-mcbopomofo` repo? As a Linux user, I'd like to receive the recent dictionary updates.

Makes sense: https://github.com/openvanilla/fcitx5-mcbopomofo/pull/143

**Pull request merged**
