### PR TITLE
Voltaire Candidate Window Beautification (swift).

### PR DESCRIPTION
**Pull request by ghost**
image
image

P.S.: McBopomofo doesn't stop me from adding duplicated user phrases.

### CODE REVIEW

**Comment by ghost** [comment]
I forgot to mention: this is my Swift reproduction of someone else's beautification towards the Objective C version of the Voltaire Candidate Window. He has his concerns to avoid leaving his names to the contributors' list of this repo.

**Comment by ghost** [comment]
@zonble Could you please help me review this if convenient?

**Comment by zonble** [comment]
1. Let's see. You are using a new GitHub account with a fake ID as a game character, filing a PR with a screenshot with my name written for three times and saying the code is from an anonymous author. It looks like you just want to say "I know who you are but you don't know who I am" to me. Personally I consider you are harassing and blackmailing me. If I should do any action, I should call the police.
2. I do not do visual design for McBopomofo. I don't think current design is especially good and I don't think it should be so called beautified either.

**Comment by AidenPearceDev** [comment]
@zonble 
1. There's no blackmailing. Mentioning you in this thread is because you are one of the main contributors who can review this.
2. MIT License already guaranteed that you are not obliged to do this. This fact has no conflicts with my intension of trying to attract someone's attention.
3. Some Formosians are really similar to Japanese, valuing personal feelings much more than valuing material facts. If you are suffering from this, may Marxism helps you feel better. This actually helped me in recent month studying Marxism.
4. This account is to make sure I can contribute without compromising my legal identity. Sorry for making you feel wrong. After reading this line, I would appreciate it if you can remove both your and my (this reply).

**Pull request closed without merging**
